### ISSUE TITLE
throw a Cannot find moudle 'react-native/setupBabel' when run react-native link

### ISSUE THREAD

**Issue by lamjack** [andpor/react-native-sqlite-storage#158]
hi, 

I am got a exception after run react-native link command, there has been no problem before..

```bash
rnpm-install info Android module react-native-localization is already linked
rnpm-install info iOS module react-native-localization is already linked
rnpm-install info Android module react-native-sound is already linked
rnpm-install info iOS module react-native-sound is already linked
rnpm-install info Android module react-native-splash-screen is already linked
rnpm-install info iOS module react-native-splash-screen is already linked
rnpm-install info iOS module react-native-sqlite-storage is already linked
module.js:472
    throw err;
    ^

Error: Cannot find module 'react-native/setupBabel'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jack/Dev/react-native/cimili/node_modules/react-native-sqlite-storage/scripts/rnpm-postlink.js:5:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
/Users/jack/Dev/react-native/cimili/node_modules/react-native/local-cli/core/makeCommand.js:29
        throw new Error(`Error occured during executing "${command}" command`);
        ^

Error: Error occured during executing "node_modules/react-native-sqlite-storage/scripts/rnpm-postlink.js" command
    at ChildProcess.prelink (/Users/jack/Dev/react-native/cimili/node_modules/react-native/local-cli/core/makeCommand.js:29:15)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```
here is my node_modules list,

```bash
├── autobind-decorator@1.4.0
├─┬ babel-jest@18.0.0
│ ├── babel-core@6.24.1
│ ├── babel-plugin-istanbul@3.1.2
│ └── babel-preset-jest@18.0.0
├─┬ babel-plugin-transform-decorators-legacy@1.3.4
│ ├── babel-plugin-syntax-decorators@6.13.0
│ ├── babel-runtime@6.23.0
│ └── babel-template@6.24.1
├─┬ babel-preset-react-native@1.9.1
│ ├── babel-plugin-check-es2015-constants@6.22.0
│ ├── babel-plugin-react-transform@2.0.2
│ ├── babel-plugin-syntax-async-functions@6.13.0
│ ├── babel-plugin-syntax-class-properties@6.13.0
│ ├── babel-plugin-syntax-flow@6.18.0
│ ├── babel-plugin-syntax-jsx@6.18.0
│ ├── babel-plugin-syntax-trailing-function-commas@6.22.0
│ ├── babel-plugin-transform-class-properties@6.24.1
│ ├── babel-plugin-transform-es2015-arrow-functions@6.22.0
│ ├── babel-plugin-transform-es2015-block-scoping@6.24.1
│ ├── babel-plugin-transform-es2015-classes@6.24.1
│ ├── babel-plugin-transform-es2015-computed-properties@6.24.1
│ ├── babel-plugin-transform-es2015-destructuring@6.23.0
│ ├── babel-plugin-transform-es2015-for-of@6.23.0
│ ├── babel-plugin-transform-es2015-function-name@6.24.1
│ ├── babel-plugin-transform-es2015-literals@6.22.0
│ ├── babel-plugin-transform-es2015-modules-commonjs@6.24.1
│ ├── babel-plugin-transform-es2015-parameters@6.24.1
│ ├── babel-plugin-transform-es2015-shorthand-properties@6.24.1
│ ├── babel-plugin-transform-es2015-spread@6.22.0
│ ├── babel-plugin-transform-es2015-template-literals@6.22.0
│ ├── babel-plugin-transform-flow-strip-types@6.22.0
│ ├── babel-plugin-transform-object-assign@6.22.0
│ ├── babel-plugin-transform-object-rest-spread@6.23.0
│ ├── babel-plugin-transform-react-display-name@6.23.0
│ ├── babel-plugin-transform-react-jsx@6.24.1
│ ├── babel-plugin-transform-react-jsx-source@6.22.0
│ ├── babel-plugin-transform-regenerator@6.24.1
│ └── react-transform-hmr@1.0.4
├── eventemitter2@2.2.2
├── eventemitter3@2.0.3
├── immutable@3.8.1
├─┬ jest@18.1.0
│ └── jest-cli@18.1.0
├── raven-js@3.14.2
├─┬ UNMET PEER DEPENDENCY react@15.4.2
│ ├── fbjs@0.8.12
│ ├── loose-envify@1.3.1
│ └── object-assign@4.1.1
├── react-immutable-proptypes@2.1.0
├─┬ react-native@0.41.2
│ ├── absolute-path@0.0.0
│ ├── art@0.10.1
│ ├── async@2.3.0
│ ├── babel-core@6.24.1 deduped
│ ├── babel-generator@6.24.1
│ ├── babel-plugin-external-helpers@6.22.0
│ ├── babel-plugin-syntax-trailing-function-commas@6.22.0 deduped
│ ├── babel-plugin-transform-flow-strip-types@6.22.0 deduped
│ ├── babel-plugin-transform-object-rest-spread@6.23.0 deduped
│ ├── babel-polyfill@6.23.0
│ ├── babel-preset-es2015-node@6.1.1
│ ├── babel-preset-fbjs@2.1.0
│ ├── babel-preset-react-native@1.9.1 deduped
│ ├── babel-register@6.24.1
│ ├── babel-runtime@6.23.0 deduped
│ ├── babel-traverse@6.24.1
│ ├── babel-types@6.24.1
│ ├── babylon@6.17.0
│ ├── base64-js@1.2.0
│ ├── bser@1.0.3
│ ├── chalk@1.1.3
│ ├── commander@2.9.0
│ ├── connect@2.30.2
│ ├── core-js@2.4.1
│ ├── debug@2.6.4
│ ├── denodeify@1.2.1
│ ├── event-target-shim@1.1.1
│ ├── fbjs@0.8.12 deduped
│ ├── fbjs-scripts@0.7.1
│ ├── fs-extra@0.26.7
│ ├── glob@5.0.15
│ ├── graceful-fs@4.1.11
│ ├── image-size@0.3.5
│ ├── immutable@3.7.6
│ ├── imurmurhash@0.1.4
│ ├── inquirer@0.12.0
│ ├── jest-haste-map@18.0.0
│ ├── joi@6.10.1
│ ├── json-stable-stringify@1.0.1
│ ├── json5@0.4.0
│ ├── left-pad@1.1.3
│ ├── lodash@4.17.4
│ ├── mime@1.3.4
│ ├── mime-types@2.1.11
│ ├── minimist@1.2.0
│ ├── mkdirp@0.5.1
│ ├── node-fetch@1.6.3
│ ├── npmlog@2.0.4
│ ├── opn@3.0.3
│ ├── optimist@0.6.1
│ ├── plist@1.2.0
│ ├── promise@7.1.1
│ ├── react-clone-referenced-element@1.0.1
│ ├── react-timer-mixin@0.13.3 deduped
│ ├── react-transform-hmr@1.0.4 deduped
│ ├── rebound@0.0.13
│ ├── regenerator-runtime@0.9.6
│ ├── request@2.81.0
│ ├── rimraf@2.6.1
│ ├── sane@1.4.1
│ ├── semver@5.3.0
│ ├── shell-quote@1.6.1
│ ├── source-map@0.5.6
│ ├── stacktrace-parser@0.1.4
│ ├── temp@0.8.3
│ ├── throat@3.0.0
│ ├── uglify-js@2.8.22
│ ├── whatwg-fetch@1.1.1
│ ├── wordwrap@1.0.0
│ ├── worker-farm@1.3.1
│ ├── write-file-atomic@1.3.3
│ ├── ws@1.1.4
│ ├── xcode@0.8.9
│ ├── xmldoc@0.4.0
│ └── yargs@6.6.0
├── react-native-image-progress@0.6.0
├─┬ react-native-lazyload@1.1.0
│ └── react-native-scrollable-mixin@1.0.1
├── react-native-localization@0.1.30
├── react-native-progress@3.2.0
├─┬ react-native-router-flux@3.38.1
│ ├── lodash.isequal@4.5.0
│ ├── UNMET PEER DEPENDENCY react@15.4.2 deduped
│ ├── react-addons-pure-render-mixin@15.5.2
│ ├── react-dom@15.5.4
│ ├── react-native@0.41.2 deduped
│ ├── react-native-experimental-navigation@0.26.12
│ ├── react-native-tabs@1.0.9
│ └── react-static-container@1.0.1
├─┬ react-native-scrollable-tab-view@0.7.4
│ ├── react-static-container@1.0.1 deduped
│ └── react-timer-mixin@0.13.3 deduped
├── react-native-sound@0.9.1
├── react-native-splash-screen@2.0.0
├─┬ react-native-sqlite-storage@3.3.1
│ └── xcode@0.8.9 deduped
├─┬ react-native-swipe-out@2.0.14
│ └── react-tween-state@0.1.5
├── react-native-swiper@1.5.4
├─┬ react-native-vector-icons@4.0.1
│ ├── lodash@4.17.4 deduped
│ └── yargs@6.6.0 deduped
├─┬ react-native-viewpager@0.2.13
│ ├── react-timer-mixin@0.13.3 deduped
│ └── warning@2.1.0
├─┬ react-native-wechat@1.9.2
│ └── events@1.0.2
├── react-native-yunpeng-alipay@1.1.4
├─┬ react-redux@5.0.4
│ ├── create-react-class@15.5.2
│ ├── hoist-non-react-statics@1.2.0
│ ├── invariant@2.2.2
│ ├── lodash@4.17.4 deduped
│ ├── lodash-es@4.17.4
│ ├── loose-envify@1.3.1 deduped
│ └── prop-types@15.5.8
├─┬ react-test-renderer@15.4.2
│ ├── fbjs@0.8.12 deduped
│ └── object-assign@4.1.1 deduped
├── react-timer-mixin@0.13.3
├─┬ redux@3.6.0
│ ├── lodash@4.17.4 deduped
│ ├── lodash-es@4.17.4 deduped
│ ├── loose-envify@1.3.1 deduped
│ └── symbol-observable@1.0.4
├─┬ redux-actions@1.2.2
│ ├── invariant@2.2.2 deduped
│ ├── lodash@4.17.4 deduped
│ └── reduce-reducers@0.1.2
├─┬ redux-persist@4.6.0
│ ├── json-stringify-safe@5.0.1
│ ├── lodash@4.17.4 deduped
│ └── lodash-es@4.17.4 deduped
├─┬ redux-persist-transform-immutable@4.2.0
│ ├── immutable@3.8.1 deduped
│ ├── transit-immutable-js@0.7.0
│ └── transit-js@0.8.846
├── redux-thunk@2.2.0
├─┬ remote-redux-devtools@0.5.7
│ ├── jsan@3.1.7
│ ├── querystring@0.2.0
│ ├── redux-devtools-instrument@1.8.0
│ ├── remotedev-utils@0.1.3
│ └── socketcluster-client@5.3.1
└─┬ url-parse@1.1.8
  ├── querystringify@0.0.4
  └── requires-port@1.0.0
```

**Comment by lamjack** [comment]
fixed, rollback the modules version.

react-native/setupBabel isn't exist in react-native 0.41.

**Comment by lmiller1990** [comment]
I am having this issue - did you roll back the react-native vers? I'd like to use the most recent react-native, is there a solution for this?

**Comment by itinance** [comment]
face this issue with RN 0.45 on a complete new project

**Comment by itinance** [comment]
Obviously setupBabel is not existing in react-native since some versions. Is there any replacement?

**Comment by itinance** [comment]
FYI: In RN 0.45.1 is setupBabel existing again.

**Comment by andpor** [comment]
Cool - I like issues that magically resolve on their own :) I am enjoying my own hell of broken XCode custom configs due to RN header changes...Cheers!

**Comment by itinance** [comment]
Oh yes! "Hell of broken XCode custom configs due to RN header changes"
Me and my other 3 developers experienced the same last days.... "react-native upgrade" helps! Just let it create a new xcodeproj-template. For sure you need to make all custom adjustments yourself again. But it will fix messed up project-files :)

**Comment by jesseteal** [comment]
This issue appears to be back for RN 0.53.0

**Comment by jesseteal** [comment]
but `rm -rf node_modules && yarn` clears it up

**Comment by 28harishkumar** [comment]
Facing same issue in:
react-native-cli: 2.0.1
react-native: 0.57.8
nodejs: v11.4.0
react: 16.6.3

**Comment by tolik85** [comment]
So how did you solve this issue?
Experiencing the same with RN 0.59.4

**Comment by deepslam** [comment]
> So how did you solve this issue?
> Experiencing the same with RN 0.59.4

+1 
I have this error too. Right now.

**Comment by scgough** [comment]
I have this in RN 0.59.4 running a non-module specific `react-native link`

**Comment by mayurssoni2456** [comment]
+1
I am facing the same error
