### ISSUE TITLE
No such table

### ISSUE THREAD

**Issue by rochapablo** [andpor/react-native-sqlite-storage#198]
I've been looking for someone with the same problem, but I couldn't find any that could resolve mine.

I'm getting success on ```SQLite.openDatabase``` but ```tx.executeSql``` throws me ```No such table```

If I run the query at SQLiteStudio it work normally

```
SELECT * FROM `development`.`transaction`
SELECT id FROM `transaction`
```

Follow my setup:

```
import SQLite from 'react-native-sqlite-storage'

    ...

    const successcb = (response) => {
      console.log(`success`, response)
    }

    const errorcb = (response) => {
      console.log(`error`, response)
    }

    const db = SQLite.openDatabase({
      name: 'development',
      createFromLocation: '~/sqlite3/development'
    }, successcb, errorcb)

    db.transaction((tx) => {
      tx.executeSql('SELECT * FROM `transaction`', [], (tx, results) => {
      // tx.executeSql('SELECT * FROM `development`.`transaction`', [], (tx, results) => {
      // tx.executeSql('SELECT * FROM sqlite_master', [], (tx, results) => {
        console.log(`results:`, results.rows)
      })
    })
```

The error

```
I/ReactNativeJS: 'success', { openargs: 
{ name: [Getter/Setter],
    createFromLocation: [Getter/Setter],
    dblocation: [Getter/Setter],
    assetFilename: [Getter/Setter] },
dbname: 'development',
openSuccess: [Function: successcb],
openError: [Function: errorcb] }
E/SQLiteLog: (1) no such table: transaction
E/unknown:SQLitePlugin: SQLitePlugin.executeSql[Batch]() failed
    android.database.sqlite.SQLiteException: no such table: transaction (code 1): , while compiling: SELECT * FROM `transaction`
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
        at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
        at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
        at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1318)
        at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1257)
        at org.pgsqlite.SQLitePlugin.executeSqlStatementQuery(SQLitePlugin.java:815)
        at org.pgsqlite.SQLitePlugin.executeSqlBatch(SQLitePlugin.java:724)
        at org.pgsqlite.SQLitePlugin.access$100(SQLitePlugin.java:49)
        at org.pgsqlite.SQLitePlugin$DBRunner.run(SQLitePlugin.java:936)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
E/unknown:SQLitePlugin: SQLitePlugin.executeSql[Batch](): failed
    android.database.sqlite.SQLiteException: no such table: transaction (code 1): , while compiling: SELECT * FROM `transaction`
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
        at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
        at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
        at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1318)
        at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1257)
        at org.pgsqlite.SQLitePlugin.executeSqlStatementQuery(SQLitePlugin.java:815)
        at org.pgsqlite.SQLitePlugin.executeSqlBatch(SQLitePlugin.java:724)
        at org.pgsqlite.SQLitePlugin.access$100(SQLitePlugin.java:49)
        at org.pgsqlite.SQLitePlugin$DBRunner.run(SQLitePlugin.java:936)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)

I/ReactNativeJS: 'Error handler not provided: ', { message: 'no such table: transaction (code 1): , while compiling: SELECT * FROM `transaction`', code: 0 }
```

```
"react": "16.0.0",
"react-native": "^0.49.3",
"react-native-infinite-scroll-view": "^0.4.3",
"react-native-sqlite-storage": "^3.3.3"
```

*Emulator Nexus 6 API 25*

What could I be missing?

**Comment by hyumus** [comment]
SQLite.openDatabase({name:"testDB.sqlite3",createFromLocation:1,location:'Library'}) . 
this solved my problem. testDB.sqlite3 file size is 24 MB. testDB.sqlite and testDB.db not working, but testDB.sqlite3 is working.

**Comment by ovaisahmed43** [comment]
> SQLite.openDatabase({name:"testDB.sqlite3",createFromLocation:1,location:'Library'}) .
> this solved my problem. testDB.sqlite3 file size is 24 MB. testDB.sqlite and testDB.db not working, but testDB.sqlite3 is working.

this works for me, thanks for sharing :)

**Comment by yasingondal** [comment]
If you are Using Emulator you will get this exception, I solved this by using real device

**Comment by toibaonguyen** [comment]
> SQLite.openDatabase({name:"testDB.sqlite3",createFromLocation:1,location:'Library'}) . this solved my problem. testDB.sqlite3 file size is 24 MB. testDB.sqlite and testDB.db not working, but testDB.sqlite3 is working.

tks brooooo
