### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by wangchj** [andpor/react-native-sqlite-storage#232]
I am writing a unit test using Jest; however, when I run `npm test`, I get the error message saying that window is no defined. Isn't the `window` object only available in a browser? I am curious why react-native-sqlite-storage is using `window` object?

The following is the output from running Jest:

```
Test suite failed to run

    ReferenceError: window is not defined
      
      at Object.<anonymous> (node_modules/react-native-sqlite-storage/lib/sqlite.core.js:53:1)
      at Object.<anonymous> (node_modules/react-native-sqlite-storage/sqlite.js:10:12)
      at Object.<anonymous> (core/db-util.js:1:177)
```

**Comment by thongnx6** [comment]
same issue

**Comment by andpor** [comment]
Not a defect in this library.
