### ISSUE TITLE
Error: Could not open database (Android, using RNFetchBlob)

### ISSUE THREAD

**Issue by jeffmon** [andpor/react-native-sqlite-storage#362]
## Your Environment
```
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
      Memory: 1.29 GB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.0.0 - ~/.nvm/versions/node/v12.0.0/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v12.0.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.3, 27.0.3, 28.0.1, 28.0.3
        System Images: android-17 | Google APIs Intel x86 Atom, android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-24 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.5 => 0.59.5
```

Using `RNFetchBlob` to download and `react-native-zip-archive` to unzip the files in either ``${RNFetchBlob.fs.dirs.DocumentDir}/www/`` or ``${RNFetchBlob.fs.dirs.MainBundleDir}/www/``.

Opening with 

```
RNFetchBlob.fs.exists(`${DATABASE_DIR}/guidid.sqlite3.db`).then(exists => {
  if (exists) {
    console.log('db is found in folder');
    SQLite.openDatabase({
      name: 'database.db',
      readonly: true,
      createFromLocation: 'guidid.sqlite3.db'
    });
}
```

And I'm getting errors opening the database. Everything is working fine on iOS but I'm getting errors on Android. 

The following are available folders for `RNFetchBlob`:

    DocumentDir
    CacheDir
    MainBundleDir (Can be used to access files embedded on iOS apps only)
    DCIMDir (Android Only)
    DownloadDir (Android Only)
    MusicDir (Android Only)
    PictureDir (Android Only)
    MovieDir (Android Only)
    RingtoneDir (Android Only)
    SDCardDir (0.9.5+ Android Only)
   
Is there another directory I should be using?

Thanks!

**Comment by andpor** [comment]
Check instructions in Readme file for the locations on Android.

**Comment by andpor** [comment]
this.getContext().getAssets().open(assetFilePath);

**Comment by andpor** [comment]
there is also native log output so why don't you include it in the issue...it should tell you where the library is looking for a database file...

**Comment by jeffmon** [comment]
I got it to work, just my Android emulator was having issues, it was all fine on my physical Android device.

Btw I used `RNFetchBlob.fs.dirs.DocumentDir` as the directory, no other folders needed.

**Comment by jeffmon** [comment]
## Native log output
```
2019-07-19 19:30:34.688 6640-7504/com.sxanpro E/unknown:SQLitePlugin: Error importing pre-populated DB asset
    java.io.IOException: write failed: ENOSPC (No space left on device)
        at libcore.io.IoBridge.write(IoBridge.java:544)
        at java.io.FileOutputStream.write(FileOutputStream.java:392)
        at org.pgsqlite.SQLitePlugin.createFromAssets(SQLitePlugin.java:453)
        at org.pgsqlite.SQLitePlugin.openDatabase(SQLitePlugin.java:399)
        at org.pgsqlite.SQLitePlugin.access$000(SQLitePlugin.java:49)
        at org.pgsqlite.SQLitePlugin$DBRunner.run(SQLitePlugin.java:904)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: android.system.ErrnoException: write failed: ENOSPC (No space left on device)
        at libcore.io.Linux.writeBytes(Native Method)
        at libcore.io.Linux.write(Linux.java:294)
        at libcore.io.ForwardingOs.write(ForwardingOs.java:241)
        at libcore.io.BlockGuardOs.write(BlockGuardOs.java:416)
        at libcore.io.ForwardingOs.write(ForwardingOs.java:241)
        at libcore.io.IoBridge.write(IoBridge.java:539)
        at java.io.FileOutputStream.write(FileOutputStream.java:392) 
        at org.pgsqlite.SQLitePlugin.createFromAssets(SQLitePlugin.java:453) 
        at org.pgsqlite.SQLitePlugin.openDatabase(SQLitePlugin.java:399) 
        at org.pgsqlite.SQLitePlugin.access$000(SQLitePlugin.java:49) 
        at org.pgsqlite.SQLitePlugin$DBRunner.run(SQLitePlugin.java:904) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
2019-07-19 19:30:34.688 6640-7504/com.sxanpro E/unknown:SQLitePlugin: Unexpected error opening database, stopping db thread
    java.lang.Exception: Error importing pre-populated DB asset
        at org.pgsqlite.SQLitePlugin.openDatabase(SQLitePlugin.java:402)
        at org.pgsqlite.SQLitePlugin.access$000(SQLitePlugin.java:49)
        at org.pgsqlite.SQLitePlugin$DBRunner.run(SQLitePlugin.java:904)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
2019-07-19 19:30:34.689 6640-7344/com.sxanpro I/ReactNativeJS: OPEN database: gudid.db failed, aborting any pending transactions
```

**Comment by CarolinaPerezFlores** [comment]
@jeffmon I have the same problem, you solved it?
