### ISSUE TITLE
Failed to update from to 3.3.11 to 4.1.0

### ISSUE THREAD

**Issue by KrzysztofSakowski** [andpor/react-native-sqlite-storage#379]
I am trying to update from to 3.3.11 to 4.1.0 and builds fails with following message.

```
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 959 file(s) to forward-jetify. Using 8 workers...
info JS server already running.
info Installing the app...

> Configure project :react-native-webview
:react-native-webview:reactNativeAndroidRoot /Users/krz/workspace/Android-app/node_modules/react-native/android

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve project :react-native-sqlite-storage.
     Required by:
         project :app
      > Unable to find a matching configuration of project :react-native-sqlite-storage:
          - None of the consumable configurations have attributes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve project :react-native-sqlite-storage.
     Required by:
         project :app
      > Unable to find a matching configuration of project :react-native-sqlite-storage:
          - None of the consumable configurations have attributes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

    at checkExecSyncError (child_process.js:616:11)
    at execFileSync (child_process.js:634:13)
    at runOnAllDevices (/Users/krz/workspace/Android-app/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:75:39)
    at buildAndRun (/Users/krz/workspace/Android-app/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:169:41)
    at then.result (/Users/krz/workspace/Android-app/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:135:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

## Your Environment
* React Native version used: react-native": "0.60.4"
* Operating System: macOS

**Comment by KrzysztofSakowski** [comment]
Removing 
```
include ':react-native-sqlite-storage'
project(':react-native-sqlite-storage').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-sqlite-storage/src/android')
```

from `android/settings.gradle` fixed the issue for me.
