### ISSUE TITLE
[Android] can't find the database

### ISSUE THREAD

**Issue by zhaoyanbing99** [andpor/react-native-sqlite-storage#85]
Android's database files should be put in any directory. I now the database file in app/src/main/assets/my.db. But when reading into error, as follows:
Android Studio log:
..................................
E/SQLitePlugin: 
unexpected error, stopping db thread  
 java.io.FileNotFoundException: /data/user/0/com.myapp/files/my.db: open failed: ENOENT (No such file or directory) at libcore.io.IoBridge.open(IoBridge.java:452)
                                                           at java.io.FileInputStream.<init>(FileInputStream.java:76)
                                                           at  org.pgsqlite.SQLitePlugin.openDatabase(SQLitePlugin.java:382)
                                                                        at org.pgsqlite.SQLitePlugin.access$000(SQLitePlugin.java:50)
                                                                        at org.pgsqlite.SQLitePlugin$DBRunner.run(SQLitePlugin.java:1031)
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                        at java.lang.Thread.run(Thread.java:818)
                                                                     Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
                                                                        at libcore.io.Posix.open(Native Method)
                                                                        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
                                                                        at libcore.io.IoBridge.open(IoBridge.java:438)
                                                                        at java.io.FileInputStream.<init>(FileInputStream.java:76) 
                                                                        at org.pgsqlite.SQLitePlugin.openDatabase(SQLitePlugin.java:382) 
                                                                        at org.pgsqlite.SQLitePlugin.access$000(SQLitePlugin.java:50) 
                                                                        at org.pgsqlite.SQLitePlugin$DBRunner.run(SQLitePlugin.java:1031) 
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                        at java.lang.Thread.run(Thread.java:818) 

My JS Code:
  ................
   var db =  SQLite.openDatabase({name : "my.db",
   readOnly: true, createFromLocation : "my.db"});
 ....................
Should I put my database file which directory ?    Thank you very much

**Comment by chandniKkpl** [comment]
I am also facing the same issue, can any one please suggest the correct way.
Thanks
